services:
  spread-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spread-dashboard
    command: streamlit run 05_apps/streamlit_app.py --server.address=0.0.0.0 --server.port=8501
    ports:
      - "8501:8501"
    volumes:
      - ./01_data:/app/01_data
      - ./06_outputs:/app/06_outputs
      - ./10_logs:/app/10_logs
    restart: unless-stopped
