server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    absolute_redirect off;

    location = / {
        return 302 /usda/;
    }

    location /usda/ {
        try_files $uri $uri/ /usda/index.html;
    }

    location ~* ^/usda/assets/ {
        expires 7d;
        add_header Cache-Control "public";
        try_files $uri =404;
    }
}
