"""Read-only development toolchain preflight for the market-data repository."""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


PYTHON_MINOR = (3, 12)
NODE_MAJOR = 24
PNPM_VERSION = "10.12.1"
RUNTIME_INPUT = "requirements.in"
RUNTIME_LOCK = "requirements.txt"
DEV_INPUT = "requirements-dev.in"
DEV_LOCK = "requirements-dev.txt"
FRONTENDS = (
    Path("11_独立应用/USDA平衡表"),
    Path("11_独立应用/OilWorld平衡表/05_apps/oil_world_dashboard"),
)


@dataclass(frozen=True)
class Check:
    status: str
    subject: str
    actual: str
    required: str
    advice: str


def _normalise_name(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def _pinned_requirements(path: Path) -> dict[str, str]:
    pins: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith(("#", "-")):
            continue
        match = re.fullmatch(
            r'([A-Za-z0-9_.-]+)(?:\[[A-Za-z0-9_.,-]+\])?==([^\\\s;]+)'
            r'(?:\s*;\s*platform_system\s*(?:==|!=)\s*"Linux")?',
            line,
        )
        if not match:
            raise ValueError(f"{path} contains a non-pinned direct dependency: {line}")
        pins[_normalise_name(match.group(1))] = match.group(2)
    return pins


def _lock_contains_pins(lock_path: Path, pins: dict[str, str]) -> bool:
    lock_text = lock_path.read_text(encoding="utf-8")
    for name, version in pins.items():
        expression = rf"(?m)^{re.escape(name)}=={re.escape(version)}(?:\s|\\)"
        if not re.search(expression, lock_text):
            return False
    return True


def check_python(root: Path, *, allow_candidate: bool) -> list[Check]:
    version = sys.version_info
    actual = f"{version[0]}.{version[1]}.{version[2]} ({sys.executable})"
    required = "Python >=3.12,<3.13 from the repository virtual environment"
    checks = [
        Check(
            "PASS" if sys.version_info[:2] == PYTHON_MINOR else "FAIL",
            "Python version",
            actual,
            required,
            "Create .venv-py312 with `py -3.12 -m venv .venv-py312`; Python 3.14 is not a formal environment.",
        )
    ]
    executable = Path(sys.executable).resolve()
    expected = (root / ".venv-py312").resolve()
    candidate = (root / ".venv-py312-candidate").resolve()
    is_formal = expected in executable.parents
    is_candidate = candidate in executable.parents
    checks.append(
        Check(
            "PASS" if is_formal or (allow_candidate and is_candidate) else "FAIL",
            "Project virtual environment",
            str(executable),
            str(expected),
            "Run this script with .venv-py312\\Scripts\\python.exe; --allow-candidate is only for migration validation.",
        )
    )
    return checks


def check_python_contract(root: Path) -> list[Check]:
    pyproject = (root / "pyproject.toml").read_text(encoding="utf-8")
    expected_python = 'requires-python = ">=3.12,<3.13"'
    checks = [
        Check(
            "PASS" if expected_python in pyproject else "FAIL",
            "pyproject Python contract",
            expected_python if expected_python in pyproject else "missing",
            expected_python,
            "Keep the canonical Python version declaration in pyproject.toml.",
        )
    ]
    for input_name, lock_name in ((RUNTIME_INPUT, RUNTIME_LOCK), (DEV_INPUT, DEV_LOCK)):
        input_path, lock_path = root / input_name, root / lock_name
        exists = input_path.is_file() and lock_path.is_file()
        if not exists:
            checks.append(Check("FAIL", f"{lock_name} contract", "missing", f"{input_name} -> {lock_name}", "Regenerate the lock with pip-compile on Python 3.12."))
            continue
        pins = _pinned_requirements(input_path)
        header_ok = "autogenerated by pip-compile with Python 3.12" in lock_path.read_text(encoding="utf-8")
        checks.append(
            Check(
                "PASS" if header_ok and _lock_contains_pins(lock_path, pins) else "FAIL",
                f"{lock_name} contract",
                f"{len(pins)} direct pins; generated={header_ok}",
                f"generated from {input_name} with Python 3.12",
                "Run pip-compile --generate-hashes for the corresponding input file.",
            )
        )
    dockerfile = (root / "Dockerfile").read_text(encoding="utf-8")
    required_install = "--require-hashes -r requirements.txt"
    checks.append(
        Check(
            "PASS" if "FROM python:3.12-slim" in dockerfile and required_install in dockerfile else "FAIL",
            "Spread Docker dependency contract",
            "python:3.12-slim with locked requirements" if required_install in dockerfile else "unlocked or missing",
            "python:3.12-slim and --require-hashes -r requirements.txt",
            "Keep Docker on the same production lock as local runtime validation.",
        )
    )
    return checks


def check_frontend_contract(root: Path) -> list[Check]:
    checks: list[Check] = []
    for relative_root in FRONTENDS:
        project_root = root / relative_root
        package_path = project_root / "package.json"
        package = json.loads(package_path.read_text(encoding="utf-8"))
        package_ok = package.get("packageManager") == f"pnpm@{PNPM_VERSION}" and package.get("engines") == {"node": ">=24 <25", "pnpm": PNPM_VERSION}
        extra_locks = [path.name for path in (project_root / "package-lock.json", project_root / "yarn.lock") if path.exists()]
        checks.append(
            Check(
                "PASS" if package_ok and (project_root / "pnpm-lock.yaml").is_file() and not extra_locks else "FAIL",
                f"{relative_root.as_posix()} package contract",
                f"packageManager={package.get('packageManager')}; extra_locks={extra_locks or 'none'}",
                f"pnpm@{PNPM_VERSION}, Node {NODE_MAJOR}.x, exactly pnpm-lock.yaml",
                "Declare the fixed pnpm version, Node engine, and retain only pnpm-lock.yaml.",
            )
        )
    for relative_dockerfile in (Path("11_独立应用/USDA平衡表/Dockerfile"), Path("11_独立应用/OilWorld平衡表/Dockerfile")):
        contents = (root / relative_dockerfile).read_text(encoding="utf-8")
        checks.append(
            Check(
                "PASS" if "FROM node:24-alpine AS build" in contents and "corepack enable" in contents and "pnpm install --frozen-lockfile" in contents else "FAIL",
                f"{relative_dockerfile.as_posix()} build contract",
                "Node 24/Corepack/frozen install" if "pnpm install --frozen-lockfile" in contents else "missing frozen install",
                "Node 24, Corepack and pnpm install --frozen-lockfile",
                "Keep local and Docker frontend installs on the packageManager-selected pnpm version.",
            )
        )
    return checks


def check_local_node_tools() -> list[Check]:
    node, corepack, pnpm = (shutil.which(name) for name in ("node", "corepack", "pnpm"))
    checks = [
        Check(
            "PASS" if node else "FAIL",
            "Node executable",
            node or "not found on PATH",
            f"Node {NODE_MAJOR}.x on standard PATH",
            "Install the declared Node 24 LTS through the approved local software process; do not use a Codex fallback.",
        ),
        Check(
            "PASS" if corepack else "FAIL",
            "Corepack executable",
            corepack or "not found on PATH",
            "Corepack provided by the declared Node 24 installation",
            "Install the declared Node 24 LTS through the approved local software process.",
        ),
    ]
    pnpm_is_fallback = bool(pnpm and "codex-runtimes" in pnpm.replace("/", "\\").lower())
    checks.append(
        Check(
            "FAIL" if pnpm_is_fallback else ("PASS" if pnpm else "FAIL"),
            "pnpm executable",
            "Codex fallback (not accepted)" if pnpm_is_fallback else (pnpm or "not found on PATH"),
            f"Corepack-managed pnpm {PNPM_VERSION}",
            "Use Corepack from the declared Node installation; the Codex fallback is intentionally not a supported contract.",
        )
    )
    if node:
        completed = subprocess.run([node, "--version"], text=True, capture_output=True, check=False)
        actual = completed.stdout.strip() or completed.stderr.strip()
        checks.append(Check("PASS" if completed.returncode == 0 and actual.startswith(f"v{NODE_MAJOR}.") else "FAIL", "Node version", actual or f"exit {completed.returncode}", f"v{NODE_MAJOR}.x", "Use the Node version declared in package.json and Dockerfile."))
    return checks


def run_checks(root: Path, *, allow_candidate: bool, scope: str = 'all') -> list[Check]:
    if scope not in {'python', 'frontend', 'all'}:
        raise ValueError('Unknown development environment scope')
    checks: list[Check] = []
    if scope in {'python', 'all'}:
        checks += check_python(root, allow_candidate=allow_candidate) + check_python_contract(root)
    if scope in {'frontend', 'all'}:
        checks += check_frontend_contract(root) + check_local_node_tools()
    return checks


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2], help="repository root (default: inferred)")
    parser.add_argument("--allow-candidate", action="store_true", help="accept .venv-py312-candidate only during one-time migration validation")
    parser.add_argument('--scope', choices=('python', 'frontend', 'all'), default='all',
                        help='check only the task toolchain; default preserves full preflight')
    args = parser.parse_args(argv)
    root = args.root.resolve()
    checks = run_checks(root, allow_candidate=args.allow_candidate, scope=args.scope)
    for check in checks:
        print(f"{check.status:4} | {check.subject}: actual={check.actual}; required={check.required}; advice={check.advice}")
    return 0 if all(check.status != "FAIL" for check in checks) else 1


if __name__ == "__main__":
    raise SystemExit(main())
