"""Provider-neutral identities and catalog access for public research data."""

from .canonical_spreads import (
    CanonicalPhysicalSeries,
    CanonicalSpreadDefinition,
    CanonicalSpreadError,
    CollapsedObservation,
    DuplicateConflictError,
    PalmCoreSixCatalog,
    ResolvedSeries,
    SpreadObservation,
    calculate_exact_inner_spread,
    collapse_source_native_duplicates,
    load_palm_core_six,
)
from .catalog import CatalogDataset, CatalogError, DataAssetCatalog, ProviderSeriesCandidate
from .identities import (
    AcquisitionChannel,
    DatasetId,
    DatasetRef,
    OriginSystem,
    Provenance,
    ProviderDatasetId,
    ProviderIdentity,
    ProviderSeriesId,
    SeriesId,
    SeriesRef,
    SourceLocator,
)
from .three_oil_v1 import (
    CanonicalSeriesContract,
    ContractObservation,
    ConversionRule,
    DerivedSeriesContract,
    FixedAssumption,
    PageDefinition,
    SpreadContract,
    ThreeOilV1Catalog,
    calculate_spread_observations,
    load_three_oil_v1,
    resolve_series_observations,
)

__all__ = [
    "AcquisitionChannel",
    "CanonicalPhysicalSeries",
    "CanonicalSeriesContract",
    "CanonicalSpreadDefinition",
    "CanonicalSpreadError",
    "CatalogDataset",
    "CatalogError",
    "CollapsedObservation",
    "ContractObservation",
    "ConversionRule",
    "DataAssetCatalog",
    "DatasetId",
    "DatasetRef",
    "DuplicateConflictError",
    "DerivedSeriesContract",
    "FixedAssumption",
    "OriginSystem",
    "PalmCoreSixCatalog",
    "PageDefinition",
    "Provenance",
    "ProviderDatasetId",
    "ProviderIdentity",
    "ProviderSeriesId",
    "ProviderSeriesCandidate",
    "ResolvedSeries",
    "SeriesId",
    "SeriesRef",
    "SourceLocator",
    "SpreadObservation",
    "SpreadContract",
    "ThreeOilV1Catalog",
    "calculate_exact_inner_spread",
    "calculate_spread_observations",
    "collapse_source_native_duplicates",
    "load_palm_core_six",
    "load_three_oil_v1",
    "resolve_series_observations",
]
