"""Provider-neutral identities and catalog access for public research data."""

from .canonical_spreads import (
    CanonicalPhysicalSeries,
    CanonicalSpreadDefinition,
    CanonicalSpreadError,
    CollapsedObservation,
    DuplicateConflictError,
    PalmCoreSixCatalog,
    ResolvedSeries,
    SpreadObservation,
    calculate_exact_inner_spread,
    collapse_source_native_duplicates,
    load_palm_core_six,
)
from .catalog import CatalogDataset, CatalogError, DataAssetCatalog, ProviderSeriesCandidate
from .identities import (
    AcquisitionChannel,
    DatasetId,
    DatasetRef,
    OriginSystem,
    Provenance,
    ProviderDatasetId,
    ProviderIdentity,
    ProviderSeriesId,
    SeriesId,
    SeriesRef,
    SourceLocator,
)

__all__ = [
    "AcquisitionChannel",
    "CanonicalPhysicalSeries",
    "CanonicalSpreadDefinition",
    "CanonicalSpreadError",
    "CatalogDataset",
    "CatalogError",
    "CollapsedObservation",
    "DataAssetCatalog",
    "DatasetId",
    "DatasetRef",
    "DuplicateConflictError",
    "OriginSystem",
    "PalmCoreSixCatalog",
    "Provenance",
    "ProviderDatasetId",
    "ProviderIdentity",
    "ProviderSeriesId",
    "ProviderSeriesCandidate",
    "ResolvedSeries",
    "SeriesId",
    "SeriesRef",
    "SourceLocator",
    "SpreadObservation",
    "calculate_exact_inner_spread",
    "collapse_source_native_duplicates",
    "load_palm_core_six",
]
